# This is a basic workflow to help you get started with Actions

name: UA/CLI Scan Run

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Downloading the Scanners
        run: |
          echo "Downloading the UA"
          curl -LJO "https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar"
          echo "Downloading the CLI"
          curl -sSL https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend

      - name: Verifying the Scanners
        run: |
          echo "Verifying the UA"
          java -jar wss-unified-agent.jar -v
          echo "Verifying the CLI"
          mend version

      - name: Running the UA
        run: java -jar wss-unified-agent.jar
        env: 
          WS_LOG_LEVEL: "DEBUG"
          WS_SHOWPROGRESSBAR: "FALSE"
          WS_PROJECTNAME: "${{ github.event.repository.name }}_${{ github.ref_name }}"
          WS_PRODUCTNAME: "${{ github.event.repository.name }}"
          WS_USERKEY: ${{ secrets.WS_USERKEY }}
          WS_APIKEY: ${{ secrets.WS_APIKEY }}
          WS_WSS_URL: ${{ secrets.MEND_URL }}
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Building Nuget
        run: |
          echo "Building Nuget"
          dotnet restore

      - name: Building Maven
        run: |
          echo "Building Maven"
          mvn clean install
           
      - name: Building NPM
        run: |
          echo "Building NPM"
          npm install

      - name: Building pip
        run: |
          echo "Building pip"
          pip install --requirement requirements.txt

      - name: Running the CLI
        run: |
          mend dep --non-interactive --extended --update --scope "Tyler_Github_Scans//${{ github.repository }}"
        env:
          MEND_USER_KEY: ${{ secrets.WS_USERKEY }}
          MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
          MEND_URL: ${{ secrets.MEND_URL }}
          MEND_LOG_LEVEL: "DEBUG"
