# This is a basic workflow to help you get started with Actions

name: UA/CLI Scan Run

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs a set of commands using the runners shell
      - name: Downloading the Scanners
        run: |
          echo "Downloading the UA"
          curl -LJO "https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar"
          echo "Downloading the CLI"
          curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend

      - name: Verifying the Scanners
        run: |
          echo "Verifying the UA"
          java -jar wss-unified-agent.jar -v
          echo "Verifying the CLI"
          mend version

      # - name: 'Running the UA'
      #   run: java -jar wss-unified-agent.jar
      #   env: 
      #     WS_LOG_LEVEL: "DEBUG"
      #     WS_SHOWPROGRESSBAR: FALSE
      #     WS_PROJECTNAME: $Build.Repository.Name_$Build.SourceBranchName
      #     WS_PRODUCTNAME: $Build.Repository.Name
      #     WS_USERKEY: $WS_USERKEY
      #     WS_APIKEY: $WS_APIKEY
      #     WS_WSS.URL: $MEND_URL
        

      - name: "Running the CLI"
        run: mend dep --non-interactive --extended --update --scope "$Build.Repository.Name//$Build.SourceBranchName"
        env:
          MEND_USER_KEY: ${{ secrets.WS_USERKEY }}
          MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
          MEND_URL: ${{ secrets.MEND_URL }}
          MEND_LOG_LEVEL: "DEBUG"
        

      
